# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-14 09:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170610_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='作者名称')),
            ],
            options={
                'verbose_name_plural': '作者',
                'verbose_name': '作者',
            },
        ),
        migrations.CreateModel(
            name='AuthorDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=30, verbose_name='城市')),
                ('country', models.CharField(max_length=30, verbose_name='国家')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Author', verbose_name='作者')),
            ],
            options={
                'verbose_name_plural': '作者详情',
                'verbose_name': '作者详情',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='书籍名称')),
                ('publish_time', models.DateField(verbose_name='出版日期')),
                ('authors', models.ManyToManyField(to='blog.Author', verbose_name='作者')),
            ],
            options={
                'verbose_name_plural': '书籍',
                'verbose_name': '书籍',
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='出版商名称', max_length=70, verbose_name='出版商名称')),
                ('city', models.CharField(help_text='城市', max_length=30, verbose_name='城市')),
                ('country', models.CharField(help_text='国家', max_length=30, verbose_name='国家')),
            ],
            options={
                'verbose_name_plural': '出版商',
                'verbose_name': '出版商',
            },
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(null=True, verbose_name='文章内容'),
        ),
        migrations.AlterField(
            model_name='article',
            name='publish_time',
            field=models.DateField(auto_now=True, verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=64, verbose_name='文章标题'),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blog.Publisher', verbose_name='出版商'),
        ),
    ]
